---

- name: restart nginx
  service: name=nginx state=restarted
  sudo: yes

- name: restart supervisor
  service: name=supervisor state=restarted
  sudo: yes

- name: restart gunicorn via supervisor
  supervisorctl: name=gunicorn state=restarted
  ignore_errors: yes
